language: php

env:
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.7.*"
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.0.*"

# We only install Mongo to ensure the container compiles properly with multiple db-drivers
before_script:
    - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - COMPOSER_ROOT_VERSION=dev-master
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer require doctrine/mongodb-odm:"1.0.*@dev" --no-update
    - composer require doctrine/mongodb-odm-bundle:"3.0.*@dev" --no-update
    - composer install

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: 7.0

script: phpunit --configuration phpunit.xml.dist --verbose --exclude-group ""
